### ISSUE TITLE
Automatically convert torches from original mod

### ISSUE THREAD

**Issue by sofar** [minetest-mods/torches#1]
self-reminder - I need to verify that torches placed and present in the world from blockmen's torches mod are properly converted through the LBM.

**Comment by verymilan** [comment]
Hi, after i saw your video i had todo a 

```
minetest.register_alias("torches:wall", "default:torch_wall")
minetest.register_alias("torches:floor","default:torch")
```

This is enough, works well. Thanks for your torches mod. :)

**Comment by sofar** [comment]
I'll check if I can't fold this into an LBM, though, but yes that will work.

**Comment by sofar** [comment]
b707f71

**Comment by sofar** [comment]
You may have to re-run the lbm. Remove any lines with `lbm` from `env_meta.txt` to let the conversion LBM run, and it will take care of any missed nodes.

**Comment by verymilan** [comment]
I currently dont know what lbm means but i'll read about it.
Your commit is very interesting, didnt know that this is possible.
(i havent updated yet but will as soon as i can)
