### ISSUE TITLE
Cannot run with this mod

### ISSUE THREAD

**Issue by luvitto** [minetest-mods/torches#12]
Got error after run with this mod

Failed to load and run script from  
/home/luvitto/.minetest/mods/torches/init.lua:
/home/luvitto/.minetest/mods/torches/init.lua:74: attempt to call field 'register_lbm' (a nil value)
stack traceback:
/home/luvitto/.minetest/mods/torches/init.lua:74: in main chunk

**Comment by sofar** [comment]
Torches requires minetest 0.4.14.
