### ISSUE TITLE
Lightspot after restart

### ISSUE THREAD

**Issue by MarkuBu** [minetest-mods/torches#3]
If you don't have the tourch in the first hotbar slot and you restart the game, than there will be a light spot at the spawn position even if you move. The spot is removed if you walk over the position.

![screenshot_20160423_201644](https://cloud.githubusercontent.com/assets/16163058/14763274/3d9f91d2-0991-11e6-864f-89f4252c1489.png)

**Comment by sofar** [comment]
Yes, this happens in singleplayer or when you're running a local server. In case the server shuts down, it doesn't call on_leave_player.

**Comment by MarkuBu** [comment]
Ok, so it is an engine problem

**Comment by sofar** [comment]
correct, I consider it as such.

**Comment by sofar** [comment]
6e02cdb
