### ISSUE TITLE
Horizontal torches

### ISSUE THREAD

**Issue by MarkuBu** [minetest-mods/torches#5]
If a torch is placed by a mapgen to a wall the torch in horizontal. 

![screenshot_20160504_161528](https://cloud.githubusercontent.com/assets/16163058/15016917/a5402fec-1213-11e6-9c6c-11aeb443b854.png)

**Comment by sofar** [comment]
Yes, the mapgen needs to place a different node in that case... It also defeated the conversion lbm.

**Comment by MarkuBu** [comment]
Which node has to be placed?

**Comment by sofar** [comment]
It should be: `default:torch_wall`

**Comment by MarkuBu** [comment]
Ok, I will open new issues to the mods where I see this, thx

**Comment by sofar** [comment]
Even though I'd _love_ to fix this, it's impossible right now.
