### ISSUE TITLE
Weildlight exposes stuttering

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/torches#6]
Caused by mesh regeneration in engine, some people may dislike such periodical stuttering. Make it off by default? Example: https://imgur.com/ypGwowQ (spikes are pretty large, from 0.007 to 0.02 or even 0.03 sec in draw time).

**Comment by sofar** [comment]
It's configurable and can be easily disabled already (minetest.conf setting)

**Comment by sofar** [comment]
Since this is a core engine, there's nothing else to do. The wieldlight has a configurable setting already.

```
torches_wieldlight_enable = false
```
