### ISSUE TITLE
error from v4 , line 68 init.lua: attempt to call field 'register_lbm' (a nil value)

### ISSUE THREAD

**Issue by tele1** [minetest-mods/torches#8]
I use
-  minetest 0.4.13
- lua 5.2.4, however I have also installed 5.1.5, I dont know which is loaded.
- torches v4 ( however with torches 3.0.1 working :-) )

debug.txt

> 2016-05-12 02:01:10: ERROR[main]: ========== ERROR FROM LUA ===========
> 2016-05-12 02:01:10: ERROR[main]: Failed to load and run script from 
> 2016-05-12 02:01:10: ERROR[main]: /home/user/.minetest/mods/torches/init.lua:
> 2016-05-12 02:01:10: ERROR[main]: /home/user/.minetest/mods/torches/init.lua:68: attempt to call field 'register_lbm' (a nil value)
> 2016-05-12 02:01:10: ERROR[main]: stack traceback:
> 2016-05-12 02:01:10: ERROR[main]:     /home/user/.minetest/mods/torches/init.lua:68: in main chunk
> 2016-05-12 02:01:10: ERROR[main]: ======= END OF ERROR FROM LUA ========
> 2016-05-12 02:01:10: ERROR[main]: Server: Failed to load and run /home/user/.minetest/mods/torches/init.lua
> 2016-05-12 02:01:10: ERROR[main]: ModError: ModError: Failed to load and run /home/user/.minetest/mods/torches/init.lua
> 2016-05-12 02:01:10: ERROR[main]: Error from Lua:
> 2016-05-12 02:01:10: ERROR[main]: /home/user/.minetest/mods/torches/init.lua:68: attempt to call field 'register_lbm' (a nil value)
> 2016-05-12 02:01:10: ERROR[main]: stack traceback:
> 2016-05-12 02:01:10: ERROR[main]:     /home/user/.minetest/mods/torches/init.lua:68: in main chunk

**Comment by sofar** [comment]
torches requires 0.4.14 or a latest dev build.

Considering that 0.4.14 is going to be released very soon, I'm not going to add compat code.

**Comment by verymilan** [comment]
@sofar i like your opinion but it might be a nice idea to leave a note in the readme :)

**Comment by sofar** [comment]
Sure:

41759e73a9d10fcd136dcd6d583fa44d63a82854

thanks.
